/**
 * This file is autogenerated by helper.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/helper/contract";

const deployedContracts = {
  11155111: {
    FHEBandChoice: {
      address: "0x49394ace9d3dDd2729a1926bFd712641e1163EAf",
      abi: [
        {
          "inputs": [],
          "name": "ZamaProtocolUnsupported",
          "type": "error"
        },
        {
          "inputs": [
            {
              "internalType": "externalEuint32",
              "name": "inputEuint32",
              "type": "bytes32"
            },
            {
              "internalType": "bytes",
              "name": "inputProof",
              "type": "bytes"
            }
          ],
          "name": "changeChoice",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "confidentialProtocolId",
          "outputs": [
            {
              "internalType": "uint256",
              "name": "",
              "type": "uint256"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "user",
              "type": "address"
            }
          ],
          "name": "hasChosen",
          "outputs": [
            {
              "internalType": "bool",
              "name": "",
              "type": "bool"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "externalEuint32",
              "name": "inputEuint32",
              "type": "bytes32"
            },
            {
              "internalType": "bytes",
              "name": "inputProof",
              "type": "bytes"
            }
          ],
          "name": "makeChoice",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "viewMyChoice",
          "outputs": [
            {
              "internalType": "euint32",
              "name": "",
              "type": "bytes32"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "user",
              "type": "address"
            }
          ],
          "name": "viewUserChoice",
          "outputs": [
            {
              "internalType": "euint32",
              "name": "",
              "type": "bytes32"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        }
      ],
      inheritedFunctions: {},
      deployedOnBlock: 9368216,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
