/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FHEBandChoiceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "changeChoice"
      | "hasChosen"
      | "makeChoice"
      | "protocolId"
      | "viewMyChoice"
      | "viewUserChoice"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "changeChoice",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasChosen",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "makeChoice",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "viewMyChoice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "viewUserChoice",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "changeChoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasChosen", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "makeChoice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "viewMyChoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewUserChoice",
    data: BytesLike
  ): Result;
}

export interface FHEBandChoice extends BaseContract {
  connect(runner?: ContractRunner | null): FHEBandChoice;
  waitForDeployment(): Promise<this>;

  interface: FHEBandChoiceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  changeChoice: TypedContractMethod<
    [inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  hasChosen: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  makeChoice: TypedContractMethod<
    [inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  viewMyChoice: TypedContractMethod<[], [string], "view">;

  viewUserChoice: TypedContractMethod<[user: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "changeChoice"
  ): TypedContractMethod<
    [inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasChosen"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "makeChoice"
  ): TypedContractMethod<
    [inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "viewMyChoice"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "viewUserChoice"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;

  filters: {};
}
