export const KPOP_GROUPS = [
    {
      id: 1,
      name: "BIGBANG",
      debut: "2006",
      members: 5,
      awards: "MAMA, Golden Disc, MTV EMA",
      description:
        "BIGBANG is a legendary K-pop group that shaped modern idol culture with timeless hits and bold individuality.",
      image: "bigbang.png",
    },
    {
      id: 2,
      name: "BTS",
      debut: "2013",
      members: 7,
      awards: "Billboard, Grammy Nominations, MAMA",
      description:
        "BTS became a worldwide phenomenon, inspiring millions with their lyrics and artistry that transcends borders.",
      image: "bts.png",
    },
    {
      id: 3,
      name: "BLACKPINK",
      debut: "2016",
      members: 4,
      awards: "MTV VMA, MAMA, Golden Disc",
      description:
        "BLACKPINK dominates the global stage with fierce charisma, fashion influence, and record-breaking performances.",
      image: "blackpink.png",
    },
    {
      id: 4,
      name: "SEVENTEEN",
      debut: "2015",
      members: 13,
      awards: "MAMA, Golden Disc, Seoul Music Awards",
      description: "SEVENTEEN shines with self-produced music, energetic choreography, and unmatched group synergy.",
      image: "seventeen.png",
    },
    {
      id: 5,
      name: "Stray Kids",
      debut: "2018",
      members: 8,
      awards: "MAMA, AAA, Golden Disc",
      description: "Stray Kids captivate with their experimental sounds and authentic self-produced music.",
      image: "straykids.png",
    },
    {
      id: 6,
      name: "TXT",
      debut: "2019",
      members: 5,
      awards: "MAMA, Golden Disc, MMA",
      description: "TXT embodies the next generation of artistry with concept-driven storytelling and emotional depth.",
      image: "txt.png",
    },
    {
      id: 7,
      name: "NewJeans",
      debut: "2022",
      members: 5,
      awards: "MAMA, Golden Disc, Seoul Music Awards",
      description: "NewJeans redefine K-pop freshness with minimalist aesthetics and Y2K-inspired vibes.",
      image: "newjeans.png",
    },
    {
      id: 8,
      name: "LE SSERAFIM",
      debut: "2022",
      members: 5,
      awards: "MAMA, Melon, Golden Disc",
      description: "LE SSERAFIM exudes confidence and elegance, becoming an emblem of modern empowerment.",
      image: "lesserafim.png",
    },
    {
      id: 9,
      name: "IVE",
      debut: "2021",
      members: 6,
      awards: "MAMA, Golden Disc, SMA",
      description: "IVE captured hearts with their elegant visuals and chart-topping anthems like 'Love Dive'.",
      image: "ive.png",
    },
    {
      id: 10,
      name: "Aespa",
      debut: "2020",
      members: 4,
      awards: "MAMA, MTV EMA, Golden Disc",
      description: "Aespa combines futuristic AI concepts and fierce energy to craft their unique digital world.",
      image: "aespa.png",
    },
    {
      id: 11,
      name: "TWICE",
      debut: "2015",
      members: 9,
      awards: "MAMA, Melon, Golden Disc",
      description:
        "TWICE’s charm and catchy tunes have solidified them as one of the most beloved girl groups worldwide.",
      image: "twice.png",
    },
    {
      id: 12,
      name: "ILLIT",
      debut: "2024",
      members: 5,
      awards: "MAMA Rookie Award",
      description: "ILLIT embodies youthful dreams and fresh visuals as a rising group in 2025’s new wave.",
      image: "illit.png",
    },
  ];
  